# This file is part of the Apathetic Guide to IdleOn project.
#
# Apathetic Tools Â© 2025 (https://github.com/apathetic-tools)
#
# This source code is dual-licensed:
#  - Under the GNU Affero General Public License v3.0 (AGPLv3).
#  - Under alternative licensing terms by the copyright holder.
#
# See `LICENSE-CODE` for details.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: "Content Contribution or Correction Report ðŸ“„"
description: "Submit new content or corrections to the guide."
labels: [
  "improve or update guide"
]
body:
  - type: markdown
    attributes:
      value: |
        <!-- 
          Reminder: If reporting a minor correction (e.g. typo), feel free to submit a PR directly!
          
          ## ðŸ’ Community
          Join our Discord: https://discord.gg/PW6GahZ7
        -->
  - type: checkboxes
    id: license
    attributes:
      label: "Thread License (required)"
      description: |
        By submitting or commenting in this thread, you assert that you have followed the guidelines in [CONTRIBUTING.md](../CONTRIBUTING.md) and agree to the project licensing terms:
        - Your contributions are your own work (or you have the right to contribute them).
        - Your contributions are licensed to the project under the same terms used by *Apathetic Tools*:
          - **Code:** [AGPL v3](../LICENSE-CODE)
          - **Content:** [CC BY-NC-SA 4.0](../LICENSE) with [No AI Use Rider](../LICENSE-NOAI-CONTENT)
        - You grant *Apathetic Tools* a perpetual, worldwide, royalty-free license to use, modify, and relicense your contribution.
      options:
        - label: "I agree to and understand the thread licensing"
          required: true
  - type: markdown
    attributes:
      value: "<!-- âš ï¸ Note: Only *Apathetic Tools* may offer alternative licensing; all other uses must follow the licenses above. -->"
  - type: input
    id: subject
    attributes:
      label: "ðŸ“š Subject area/topic"
      description: "Area of the guide or topic your contribution affects"
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: page
    attributes:
      label: "ðŸ“‹ Page(s) affected (or proposed for new content)"
      description: "Please provide the URL of the page(s) affected or the suggested location for new content."
      placeholder: "https://apathetic-idleon.github.io/walkthrough/getting-started/"
    validations:
      required: true
  - type: textarea
    id: generalDesc
    attributes:
      label: "ðŸ“‹ Description of contribution or correction"
      description: "Describe the correction or provide the new content you want to add"
      placeholder: "Include the text, images, or instructions here..."
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: "Source / Verification"
      description: "How can we verify this correction or content is accurate?"
      placeholder: "Include references, screenshots, or steps if applicable"
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots (optional)"
      description: "If applicable, add screenshots to help corroborate your submission"
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "ðŸ“„ Additional Information (optional)"
      description: "Any additional information that may be relevant for your submission."
    validations:
      required: false      
  - type: input
    id: contact
    attributes:
      label: "Discord Contact (optional)"
      description: "If you are a member of the Apathetic Tools Discord (https://discord.gg/PW6GahZ7), please add your username below so we can welcome you there!"
      placeholder: "Username"
    validations:
      required: false
