# This file is part of the Apathetic Guide to IdleOn project.
#
# Apathetic Tools © 2025 (https://github.com/apathetic-tools)
#
# This source code is dual-licensed:
#  - Under the GNU Affero General Public License v3.0 (AGPLv3).
#  - Under alternative licensing terms by the copyright holder.
#
# See `LICENSE-CODE` for details.
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Inspired by withastro/starlight · MIT
# https://github.com/withastro/starlight/blob/main/.github/ISSUE_TEMPLATE/---01-bug-report.yml

name: "📄 Content Contribution or Correction Report"
description: "   Submit new content or corrections to the guide."
labels: [
  "improve or update guide"
]
body:
  - type: markdown
    attributes:
      value: |
          #### Reminder: If reporting a minor correction (e.g. typo), feel free to submit a PR directly!
          
          Thank you for taking the time to share your contribution! Please fill out this form as completely as possible.          
          
          ### Community
          Join our Discord: https://discord.gg/PW6GahZ7
  - type: checkboxes
    id: license
    attributes:
      label: "Thread License (required)"
      description: |
        By submitting or commenting in this thread, you assert that you have followed the guidelines in [CONTRIBUTING.md](../CONTRIBUTING.md) and agree to the project licensing terms:
        - Your contributions are your own work (or you have the right to contribute them).
        - Your contributions are licensed to the project under the same terms used by *Apathetic Tools*:
          - **Code:** [AGPL v3](../LICENSE-CODE)
          - **Content:** [CC BY-NC-SA 4.0](../LICENSE) with [No AI Use Rider](../LICENSE-NOAI-CONTENT)
        - You grant *Apathetic Tools* a perpetual, worldwide, royalty-free license to use, modify, and relicense your contribution.

        **Note:** Only *Apathetic Tools* may offer alternative licensing; all other uses must follow the licenses above.
      options:
        - label: "I agree to and understand the thread licensing"
          required: true
  - type: textarea
    id: page
    attributes:
      label: "What page of the guide does this affect?"
      description: "If this applies to multiple pages, include additional pages in your description."
      placeholder: "https://apathetic-idleon.github.io/journey/getting-started/..."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Describe your contribution or correction"
      description: "A clear and concise description of your contribution."
      placeholder: "Include the text, images, or instructions here..."
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: "Source / Verification"
      description: "How can we verify this correction or content is accurate?"
      placeholder: "Include references, screenshots, or steps if applicable"
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots (optional)"
      description: "If applicable, add screenshots to help corroborate your submission"
    validations:
      required: false
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false  
  - type: input
    id: contact
    attributes:
      label: "Discord Contact (optional)"
      description: "If you are a member of the 👾 [*Apathetic Tools Discord*](https://discord.gg/PW6GahZ7), please add your username below so we can welcome you there!"
      placeholder: "Username"
    validations:
      required: false
