# This file is part of the Apathetic Guide to IdleOn project.
#
# Apathetic Tools © 2025 (https://github.com/apathetic-tools)
#
# This source code is dual-licensed:
#  - Under the GNU Affero General Public License v3.0 (AGPLv3).
#  - Under alternative licensing terms by the copyright holder.
#
# See `LICENSE-CODE` for details.
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Inspired by withastro/starlight · MIT
# https://github.com/withastro/starlight/blob/main/.github/ISSUE_TEMPLATE/---01-bug-report.yml

name: "Bug Report 🐛"
description: "Report an issue or possible bug with the functionality of the guide website (not related to guide content)."
labels: [
  "bug"
]
body:
  - type: markdown
    attributes:
      value: |
          Thank you for taking the time to file a bug report! Please fill out this form as completely as possible.

          ### Community
          Join our Discord: https://discord.gg/PW6GahZ7
  - type: checkboxes
    id: license
    attributes:
      label: "Thread License (required)"
      description: |
        By submitting or commenting in this thread, you assert that you have followed the guidelines in [CONTRIBUTING.md](../CONTRIBUTING.md) and agree to the project licensing terms:
        - Your contributions are your own work (or you have the right to contribute them).
        - Your contributions are licensed to the project under the same terms used by *Apathetic Tools*:
          - **Code:** [AGPL v3](../LICENSE-CODE)
          - **Content:** [CC BY-NC-SA 4.0](../LICENSE) with [No AI Use Rider](../LICENSE-NOAI-CONTENT)
        - You grant *Apathetic Tools* a perpetual, worldwide, royalty-free license to use, modify, and relicense your contribution.
      options:
        - label: "I agree to and understand the thread licensing"
          required: true
  - type: markdown
    attributes:
      value: "**Note:** Only *Apathetic Tools* may offer alternative licensing; all other uses must follow the licenses above."
  - type: textarea
    id: page
    attributes:
      label: "What page of the guide did you find an issue on?"
      description: "If this issue applies to multiple pages, include additional pages in your bug description."
      placeholder: "https://apathetic-idleon.github.io/journey/getting-started/..."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Describe the Bug"
      description: "A clear and concise description of what the issue is."
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: What operating system are you using?
      placeholder: Mac, Windows, Linux
    validations:
      required: true      
  - type: input
    id: browser
    attributes:
      label: "Browser"
      description: "What browser are you using?"
      placeholder: "Chrome, Firefox, Safari"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots (optional)"
      description: "If applicable, add screenshots to help illustrate the problem."
    validations:
      required: false
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false      
  - type: input
    id: contact
    attributes:
      label: "Discord Contact (optional)"
      description: "If you are a member of the 👾 [*Apathetic Tools Discord*](https://discord.gg/PW6GahZ7), please add your username below so we can welcome you there!"
      placeholder: "Username"
    validations:
      required: false
