name: "Incorrect Content Report 📄"
description: "Report a correction to the guide content."
labels: [
  "improve or update guide"
]
body:
  - type: markdown
    attributes:
      value: "# Reminder: If reporting a minor correction (e.g. typo), feel free to submit a PR directly!"
  - type: checkboxes
    id: license
    attributes:
      label: "Thread License (required)"
      description: |
        *Thread Licenses do not override the IdleOn game or project licenses.*
        - Any diff, additions, changes, deletions, or contributions to code within this thread is licensed under the [MIT License](https://opensource.org/license/mit).
        - Any diff, additions, changes, deletions, or contributions of text, animations, images, videos, or other assets within this thread is licensed under the [Creative Commons Attribution 4.0 Internaltion](https://creativecommons.org/licenses/by/4.0/deed.en) license."      
      options:
        - label: "I agree to and understand the licensing"
          required: true
  - type: input
    id: subject
    attributes:
      label: 📚 Subject area/topic
      description: Guide area/topic
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: page
    attributes:
      label: "📋 Page(s) affected (or suggested, for new content)"
      description: Please provide the URL of the page(s) affected.
      placeholder: https://apathetic-idleon.github.io/journey/getting-started/
    validations:
        required: true
  - type: textarea
    id: generalDesc
    attributes:
      label: "📋 Description of content that is out-of-date or incorrect"
      description: Let us know what's wrong!
      placeholder: "..."
    validations:
        required: true
  - type: textarea
    id: source
    attributes:
      label: "Steps to obtain the information to verify your correction"
      description: Let us know how we can verify your information for ourselves!
      placeholder: "..."
    validations:
        required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help corroborate your source.
    validations:
        required: false
  - type: textarea
    id: additional
    attributes:
      label: "📄 Additional Information"
      description: Any additional information that may be relevant for the issue.
    validations:
      required: false  
  - type: input
    id: contact
    attributes:
      label: Discord Contact (optional)
      description: If you are a member of the Apathetic Tools Discord (https://discord.gg/PW6GahZ7), please add your username in the description so we can welcome you there!
      placeholder: InertSloth
    validations:
      required: false
