# https://docs.astro.build/en/guides/deploy/github/
# https://github.com/peaceiris/actions-gh-pages
name: Deploy to GitHub Pages

# to create your key:
#   ssh-keygen -t ed25519 -a 100 -f path/to/keyfile -N "" -C "github-actions"
# make sure no passphrase, can't get prompted in github secret

# if you need older rsa method for older servers:
#   ssh-keygen -t rsa -b 4096 -o -f path/to/keyfile -N "" -C "github-actions"

# on the source repo: add the private key file contents without an extension to ACTIONS_DEPLOY_KEY secrets
#   repo -> settings -> environments -> github-pages -> Environment secrets -> add ACTIONS_DEPLOY_KEY secret -> paste in contents
# make sure there is a trailing newline at the end. It will fail otherwise.
# also, if you use environment secret here, you need to use `environment: github-pages` below. Otherwise use a repository secret instead.

# on the destination repo: add the file contents of the .pub file to deploy keys
#   repo -> settings -> Security header -> Deploy keys -> Add deploy key -> check write access

# make sure both files use linux LF characters, not windows ones.
# if you have a copy paste / clipboard utility or some other program it may mangle the contents.

# if you private key does not have `BEGIN OPENSSH PRIVATE KEY` in header you NEED to convert to PEM (make a backup of your key first):
#   ssh-keygen -p -f path/to/your/key -m pem

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  # pages: write # since we are ssh pushing, don't need this
  # id-token: write # since we are ssh pushing, don't need this

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          # path: . # The root location of your Astro project inside the repository. (optional)
          node-version: 22.19.0 # The specific version of Node that should be used to build your site. Defaults to 20. (optional)
          # package-manager: pnpm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
        # env:
        # PUBLIC_POKEAPI: 'https://pokeapi.co/api/v2' # Use single quotation marks for the variable value. (optional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./dist
          enable_jekyll: false
          external_repository: apathetic-idleon/apathetic-idleon.github.io
        if: ${{ github.ref == 'refs/heads/main' }} # only deploy main